//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFlightbook.FlightProperties.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PropertyResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertyResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyFlightbook.FlightProperties.Properties.PropertyResource", typeof(PropertyResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} approach.
        /// </summary>
        public static string ApproachDescApproach {
            get {
                return ResourceManager.GetString("ApproachDescApproach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} approaches.
        /// </summary>
        public static string ApproachDescApproaches {
            get {
                return ResourceManager.GetString("ApproachDescApproaches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} to runway {1} at {2}.
        /// </summary>
        public static string ApproachDescTemplate {
            get {
                return ResourceManager.GetString("ApproachDescTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        public static string CompareAdded {
            get {
                return ResourceManager.GetString("CompareAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string CompareDeleted {
            get {
                return ResourceManager.GetString("CompareDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        public static string CompareModified {
            get {
                return ResourceManager.GetString("CompareModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified (leading/trailing whitespace only).
        /// </summary>
        public static string CompareModifiedWhitespace {
            get {
                return ResourceManager.GetString("CompareModifiedWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block: {0}.
        /// </summary>
        public static string ElapsedBlockSummary {
            get {
                return ResourceManager.GetString("ElapsedBlockSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty: {0}.
        /// </summary>
        public static string ElapsedDutySummary {
            get {
                return ResourceManager.GetString("ElapsedDutySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight Duty: {0}.
        /// </summary>
        public static string ElapsedFlightDutySummary {
            get {
                return ResourceManager.GetString("ElapsedFlightDutySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson: {0}.
        /// </summary>
        public static string ElapsedLessonSummary {
            get {
                return ResourceManager.GetString("ElapsedLessonSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled: {0}.
        /// </summary>
        public static string ElapsedScheduleSummary {
            get {
                return ResourceManager.GetString("ElapsedScheduleSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tach: {0}.
        /// </summary>
        public static string ElapsedTachSummary {
            get {
                return ResourceManager.GetString("ElapsedTachSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} to {1} ({2}).
        /// </summary>
        public static string ElapsedTime {
            get {
                return ResourceManager.GetString("ElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template description cannot exceed 255 characters..
        /// </summary>
        public static string errTemplateDescriptionTooLong {
            get {
                return ResourceManager.GetString("errTemplateDescriptionTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template requires a name.
        /// </summary>
        public static string errTemplateNoName {
            get {
                return ResourceManager.GetString("errTemplateNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template is empty - need to have at least one property..
        /// </summary>
        public static string errTemplateNoProperties {
            get {
                return ResourceManager.GetString("errTemplateNoProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes/No.
        /// </summary>
        public static string importUnitBoolean {
            get {
                return ResourceManager.GetString("importUnitBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string importUnitDate {
            get {
                return ResourceManager.GetString("importUnitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string importUnitNumber {
            get {
                return ResourceManager.GetString("importUnitNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string importUnitText {
            get {
                return ResourceManager.GetString("importUnitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string PropertyNo {
            get {
                return ResourceManager.GetString("PropertyNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string PropertyYes {
            get {
                return ResourceManager.GetString("PropertyYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous Aircraft (Basic).
        /// </summary>
        public static string TemplateAnonymousBasic {
            get {
                return ResourceManager.GetString("TemplateAnonymousBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains properties useful for flights in anonymous aircraft.
        /// </summary>
        public static string TemplateAnonymousBasicDesc {
            get {
                return ResourceManager.GetString("TemplateAnonymousBasicDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string templateGroupAuto {
            get {
                return ResourceManager.GetString("templateGroupAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkrides and Reviews.
        /// </summary>
        public static string templateGroupCheckrides {
            get {
                return ResourceManager.GetString("templateGroupCheckrides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson Plans.
        /// </summary>
        public static string templateGroupLessons {
            get {
                return ResourceManager.GetString("templateGroupLessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missions.
        /// </summary>
        public static string templateGroupMissions {
            get {
                return ResourceManager.GetString("templateGroupMissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string templateGroupRole {
            get {
                return ResourceManager.GetString("templateGroupRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training.
        /// </summary>
        public static string templateGroupTraining {
            get {
                return ResourceManager.GetString("templateGroupTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previously Used.
        /// </summary>
        public static string TemplateMRU {
            get {
                return ResourceManager.GetString("TemplateMRU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically shows properties you&apos;ve used on previous flights.  You can remove ones you no longer need..
        /// </summary>
        public static string TemplateMRUDescription {
            get {
                return ResourceManager.GetString("TemplateMRUDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulator / Training Device (Basic).
        /// </summary>
        public static string TemplateSimBasic {
            get {
                return ResourceManager.GetString("TemplateSimBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains properties useful for any sort of simulator flight.
        /// </summary>
        public static string TemplateSimBasicDesc {
            get {
                return ResourceManager.GetString("TemplateSimBasicDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string TemplateStudent {
            get {
                return ResourceManager.GetString("TemplateStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains properties useful for students.
        /// </summary>
        public static string TemplateStudentDesc {
            get {
                return ResourceManager.GetString("TemplateStudentDesc", resourceCulture);
            }
        }
    }
}
