//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Member_FlightAnalysis
{

    /// <summary>
    /// Master property.
    /// </summary>
    /// <remarks>
    /// Auto-generated property.
    /// </remarks>
    public new MyFlightbook.Web.MasterPage Master
    {
        get
        {
            return ((MyFlightbook.Web.MasterPage)(base.Master));
        }
    }
}
