//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Admin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Admin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Admin", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have chosen to subscribe to the topic arn:aws:sns:us-west-2:123456789012:MyTopic.\nTo confirm the subscription, visit the SubscribeURL included in this message..
        /// </summary>
        internal static string AWSSubscriptionTestMessage {
            get {
                return ResourceManager.GetString("AWSSubscriptionTestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} dupes found.
        /// </summary>
        internal static string DupesFound {
            get {
                return ResourceManager.GetString("DupesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing rows {0}-{1} of {2}.
        /// </summary>
        internal static string ImageRowsHeader {
            get {
                return ResourceManager.GetString("ImageRowsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Distance: {0:f1}nm&lt;br /&gt;&quot;.
        /// </summary>
        internal static string ImportAirportDistanceTemplate {
            get {
                return ResourceManager.GetString("ImportAirportDistanceTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Status: {0}&lt;br /&gt;&quot;.
        /// </summary>
        internal static string ImportAirportStatusTemplate {
            get {
                return ResourceManager.GetString("ImportAirportStatusTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files comprising {1:#,##0} bytes moved.
        /// </summary>
        internal static string MigrateImagesTemplate {
            get {
                return ResourceManager.GetString("MigrateImagesTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No dupes found.
        /// </summary>
        internal static string NoDupesFound {
            get {
                return ResourceManager.GetString("NoDupesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sims found.
        /// </summary>
        internal static string SimsFoundTemplate {
            get {
                return ResourceManager.GetString("SimsFoundTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site States for: {0}.
        /// </summary>
        internal static string SiteStatsTemplate {
            get {
                return ResourceManager.GetString("SiteStatsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}, {1:F1}°&quot;.
        /// </summary>
        internal static string SolarAngleTimeTemplate {
            get {
                return ResourceManager.GetString("SolarAngleTimeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}UTC).
        /// </summary>
        internal static string SunriseSunsetTemplate {
            get {
                return ResourceManager.GetString("SunriseSunsetTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Registration for {0}.
        /// </summary>
        internal static string ViewRegistrationTemplate {
            get {
                return ResourceManager.GetString("ViewRegistrationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0} of {1} segments examined&quot;.
        /// </summary>
        internal static string VisitedRoutesExaminedTemplate {
            get {
                return ResourceManager.GetString("VisitedRoutesExaminedTemplate", resourceCulture);
            }
        }
    }
}
