//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FlightQuery {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FlightQuery() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.FlightQuery", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex.
        /// </summary>
        internal static string AircraftFeatureComplex {
            get {
                return ResourceManager.GetString("AircraftFeatureComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant speed props.
        /// </summary>
        internal static string AircraftFeatureConstantSpeedProp {
            get {
                return ResourceManager.GetString("AircraftFeatureConstantSpeedProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric.
        /// </summary>
        internal static string AircraftFeatureElectric {
            get {
                return ResourceManager.GetString("AircraftFeatureElectric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flaps.
        /// </summary>
        internal static string AircraftFeatureFlaps {
            get {
                return ResourceManager.GetString("AircraftFeatureFlaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glass Cockpit.
        /// </summary>
        internal static string AircraftFeatureGlass {
            get {
                return ResourceManager.GetString("AircraftFeatureGlass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High performance.
        /// </summary>
        internal static string AircraftFeatureHighPerformance {
            get {
                return ResourceManager.GetString("AircraftFeatureHighPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jet.
        /// </summary>
        internal static string AircraftFeatureJet {
            get {
                return ResourceManager.GetString("AircraftFeatureJet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor Glider or TMG.
        /// </summary>
        internal static string AircraftFeatureMotorGlider {
            get {
                return ResourceManager.GetString("AircraftFeatureMotorGlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-engine Helicopter.
        /// </summary>
        internal static string AircraftFeatureMultiEngineHelicopter {
            get {
                return ResourceManager.GetString("AircraftFeatureMultiEngineHelicopter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piston.
        /// </summary>
        internal static string AircraftFeaturePiston {
            get {
                return ResourceManager.GetString("AircraftFeaturePiston", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Aircraft.
        /// </summary>
        internal static string AircraftFeatureReal {
            get {
                return ResourceManager.GetString("AircraftFeatureReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retractable gear.
        /// </summary>
        internal static string AircraftFeatureRetractableGear {
            get {
                return ResourceManager.GetString("AircraftFeatureRetractableGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technically Advanced Aircraft (TAA).
        /// </summary>
        internal static string AircraftFeatureTAA {
            get {
                return ResourceManager.GetString("AircraftFeatureTAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tailwheel.
        /// </summary>
        internal static string AircraftFeatureTailwheel {
            get {
                return ResourceManager.GetString("AircraftFeatureTailwheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Device (Simulator, FTD, ATD).
        /// </summary>
        internal static string AircraftFeatureTrainingDevice {
            get {
                return ResourceManager.GetString("AircraftFeatureTrainingDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turbine (Any).
        /// </summary>
        internal static string AircraftFeatureTurbine {
            get {
                return ResourceManager.GetString("AircraftFeatureTurbine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turboprop.
        /// </summary>
        internal static string AircraftFeatureTurboprop {
            get {
                return ResourceManager.GetString("AircraftFeatureTurboprop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft type.
        /// </summary>
        internal static string AircraftFeatureType {
            get {
                return ResourceManager.GetString("AircraftFeatureType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category/class is one of.
        /// </summary>
        internal static string CategoryClass {
            get {
                return ResourceManager.GetString("CategoryClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string ConjunctionAll {
            get {
                return ResourceManager.GetString("ConjunctionAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        internal static string ConjunctionAny {
            get {
                return ResourceManager.GetString("ConjunctionAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string ConjunctionNone {
            get {
                return ResourceManager.GetString("ConjunctionNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight has .
        /// </summary>
        internal static string ConjunctionPrompt1 {
            get {
                return ResourceManager.GetString("ConjunctionPrompt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of the following:.
        /// </summary>
        internal static string ConjunctionPrompt2 {
            get {
                return ResourceManager.GetString("ConjunctionPrompt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft.
        /// </summary>
        internal static string ContainsAircraft {
            get {
                return ResourceManager.GetString("ContainsAircraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airports.
        /// </summary>
        internal static string ContainsAirports {
            get {
                return ResourceManager.GetString("ContainsAirports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make/model.
        /// </summary>
        internal static string ContainsMakeModel {
            get {
                return ResourceManager.GetString("ContainsMakeModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make/model contains.
        /// </summary>
        internal static string ContainsMakeModelText {
            get {
                return ResourceManager.GetString("ContainsMakeModelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR make/model contains.
        /// </summary>
        internal static string ContainsMakeModelTextOR {
            get {
                return ResourceManager.GetString("ContainsMakeModelTextOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains words.
        /// </summary>
        internal static string ContainsText {
            get {
                return ResourceManager.GetString("ContainsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type is.
        /// </summary>
        internal static string ContainsType {
            get {
                return ResourceManager.GetString("ContainsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type is one of.
        /// </summary>
        internal static string ContainsTypeMultiple {
            get {
                return ResourceManager.GetString("ContainsTypeMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none).
        /// </summary>
        internal static string ContainsTypeNone {
            get {
                return ResourceManager.GetString("ContainsTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After {0}.
        /// </summary>
        internal static string DatesAfter {
            get {
                return ResourceManager.GetString("DatesAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string DatesAll {
            get {
                return ResourceManager.GetString("DatesAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before: {0}.
        /// </summary>
        internal static string DatesBefore {
            get {
                return ResourceManager.GetString("DatesBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Between {0} and {1}.
        /// </summary>
        internal static string DatesBetween {
            get {
                return ResourceManager.GetString("DatesBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past 12 months.
        /// </summary>
        internal static string DatesPrev12Month {
            get {
                return ResourceManager.GetString("DatesPrev12Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past 30 days.
        /// </summary>
        internal static string DatesPrev30Days {
            get {
                return ResourceManager.GetString("DatesPrev30Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past 6 months.
        /// </summary>
        internal static string DatesPrev6Month {
            get {
                return ResourceManager.GetString("DatesPrev6Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past 90 days.
        /// </summary>
        internal static string DatesPrev90Days {
            get {
                return ResourceManager.GetString("DatesPrev90Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous month.
        /// </summary>
        internal static string DatesPrevMonth {
            get {
                return ResourceManager.GetString("DatesPrevMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous year.
        /// </summary>
        internal static string DatesPrevYear {
            get {
                return ResourceManager.GetString("DatesPrevYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This month.
        /// </summary>
        internal static string DatesThisMonth {
            get {
                return ResourceManager.GetString("DatesThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year to date.
        /// </summary>
        internal static string DatesYearToDate {
            get {
                return ResourceManager.GetString("DatesYearToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates.
        /// </summary>
        internal static string FilterDate {
            get {
                return ResourceManager.GetString("FilterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight range.
        /// </summary>
        internal static string FilterFlightRange {
            get {
                return ResourceManager.GetString("FilterFlightRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Flights.
        /// </summary>
        internal static string FilterNone {
            get {
                return ResourceManager.GetString("FilterNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight has characteristics ({0}).
        /// </summary>
        internal static string FlightCharacteristics {
            get {
                return ResourceManager.GetString("FlightCharacteristics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holding procedures.
        /// </summary>
        internal static string FlightFeatureaHolds {
            get {
                return ResourceManager.GetString("FlightFeatureaHolds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument time.
        /// </summary>
        internal static string FlightFeatureAnyInstrument {
            get {
                return ResourceManager.GetString("FlightFeatureAnyInstrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landings.
        /// </summary>
        internal static string FlightFeatureAnyLandings {
            get {
                return ResourceManager.GetString("FlightFeatureAnyLandings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approaches.
        /// </summary>
        internal static string FlightFeatureApproaches {
            get {
                return ResourceManager.GetString("FlightFeatureApproaches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CFI time.
        /// </summary>
        internal static string FlightFeatureCFI {
            get {
                return ResourceManager.GetString("FlightFeatureCFI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dual time.
        /// </summary>
        internal static string FlightFeatureDual {
            get {
                return ResourceManager.GetString("FlightFeatureDual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full-stop day landings.
        /// </summary>
        internal static string FlightFeatureFSLanding {
            get {
                return ResourceManager.GetString("FlightFeatureFSLanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full-stop nighttime landings.
        /// </summary>
        internal static string FlightFeatureFSNightLanding {
            get {
                return ResourceManager.GetString("FlightFeatureFSNightLanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ground simulator time.
        /// </summary>
        internal static string FlightFeatureGroundsim {
            get {
                return ResourceManager.GetString("FlightFeatureGroundsim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images or videos.
        /// </summary>
        internal static string FlightFeatureHasImages {
            get {
                return ResourceManager.GetString("FlightFeatureHasImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has telemetry.
        /// </summary>
        internal static string FlightFeatureHasTelemetry {
            get {
                return ResourceManager.GetString("FlightFeatureHasTelemetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual IMC time.
        /// </summary>
        internal static string FlightFeatureIMC {
            get {
                return ResourceManager.GetString("FlightFeatureIMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed.
        /// </summary>
        internal static string FlightFeatureIsSigned {
            get {
                return ResourceManager.GetString("FlightFeatureIsSigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night flight.
        /// </summary>
        internal static string FlightFeatureNight {
            get {
                return ResourceManager.GetString("FlightFeatureNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIC time.
        /// </summary>
        internal static string FlightFeaturePIC {
            get {
                return ResourceManager.GetString("FlightFeaturePIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible to others.
        /// </summary>
        internal static string FlightFeaturePublic {
            get {
                return ResourceManager.GetString("FlightFeaturePublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SICtime.
        /// </summary>
        internal static string FlightFeatureSIC {
            get {
                return ResourceManager.GetString("FlightFeatureSIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulated IMC time.
        /// </summary>
        internal static string FlightFeatureSimIMC {
            get {
                return ResourceManager.GetString("FlightFeatureSimIMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Time.
        /// </summary>
        internal static string FlightFeatureTotalTime {
            get {
                return ResourceManager.GetString("FlightFeatureTotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross-country time.
        /// </summary>
        internal static string FlightFeatureXC {
            get {
                return ResourceManager.GetString("FlightFeatureXC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight has these properties ({0}).
        /// </summary>
        internal static string FlightHasProperties {
            get {
                return ResourceManager.GetString("FlightHasProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local flights only.
        /// </summary>
        internal static string FlightRangeLocal {
            get {
                return ResourceManager.GetString("FlightRangeLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-local flights only.
        /// </summary>
        internal static string FlightRangeNonLocal {
            get {
                return ResourceManager.GetString("FlightRangeNonLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name this query for future use:.
        /// </summary>
        internal static string SaveQueryNamePrompt {
            get {
                return ResourceManager.GetString("SaveQueryNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no saved queries.
        /// </summary>
        internal static string SaveQueryNoSavedQueries {
            get {
                return ResourceManager.GetString("SaveQueryNoSavedQueries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save....
        /// </summary>
        internal static string SaveQueryPrompt {
            get {
                return ResourceManager.GetString("SaveQueryPrompt", resourceCulture);
            }
        }
    }
}
