//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Profile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Profile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Profile", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %APP_NAME% can save a backup spreadsheet of your logbook to your cloud drive account.
        /// </summary>
        internal static string AboutCloudStorage {
            get {
                return ResourceManager.GetString("AboutCloudStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only sign in or do a password reset using your account&apos;s main email address.  However, additional verified addresses may be used for sharing flights, requests to sign flights, or requests to set up a student/instructor relationship..
        /// </summary>
        internal static string accountAlternativeAddressDescription {
            get {
                return ResourceManager.GetString("accountAlternativeAddressDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified address(es) are below..
        /// </summary>
        internal static string accountAlternativeVerifiedAddresses {
            get {
                return ResourceManager.GetString("accountAlternativeVerifiedAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number:.
        /// </summary>
        internal static string accountCellPhone {
            get {
                return ResourceManager.GetString("accountCellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Optional; can help with password reset or if you are in a club).
        /// </summary>
        internal static string accountCellPhoneHint {
            get {
                return ResourceManager.GetString("accountCellPhoneHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        internal static string accountDateOfBirth {
            get {
                return ResourceManager.GetString("accountDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Optional, but required in some jurisdictions; Used when printing or computing medical duration).
        /// </summary>
        internal static string accountDateOfBirthPromptNote {
            get {
                return ResourceManager.GetString("accountDateOfBirthPromptNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an alternate email.
        /// </summary>
        internal static string accountEmailAddAlias {
            get {
                return ResourceManager.GetString("accountEmailAddAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this alternative email (alias).
        /// </summary>
        internal static string accountEmailAliasDelete {
            get {
                return ResourceManager.GetString("accountEmailAliasDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this email alias?  This cannot be undone..
        /// </summary>
        internal static string accountEmailAliasDeleteConfirm {
            get {
                return ResourceManager.GetString("accountEmailAliasDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate emails.
        /// </summary>
        internal static string accountEmailAliasesHeader {
            get {
                return ResourceManager.GetString("accountEmailAliasesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pilots may reach out to other pilots to sign flights, share flights, request club membership, or set up a student/instructor relationship.  These messages are encrypted to be usable only by the recipient.  Adding an alternate email allows them to send to you at a secondary email address (e.g., if you have a business and a personal email), yet still allows you to handle the request in your account.  You CANNOT SIGN IN using any of these addresses..
        /// </summary>
        internal static string accountEmailAliasWhy {
            get {
                return ResourceManager.GetString("accountEmailAliasWhy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string accountEmailPrompt {
            get {
                return ResourceManager.GetString("accountEmailPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First (Given) Name.
        /// </summary>
        internal static string accountFirstNamePrompt {
            get {
                return ResourceManager.GetString("accountFirstNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Settings.
        /// </summary>
        internal static string accountHeader {
            get {
                return ResourceManager.GetString("accountHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an image of yourself! .
        /// </summary>
        internal static string accountHeadShot {
            get {
                return ResourceManager.GetString("accountHeadShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Optional; headshots work best.).
        /// </summary>
        internal static string accountHeadShotHint {
            get {
                return ResourceManager.GetString("accountHeadShotHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Account is locked.
        /// </summary>
        internal static string AccountIsLockedSubject {
            get {
                return ResourceManager.GetString("AccountIsLockedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last (Family) Name.
        /// </summary>
        internal static string accountLastNamePrompt {
            get {
                return ResourceManager.GetString("accountLastNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing Address.
        /// </summary>
        internal static string accountMailingAddressPrompt {
            get {
                return ResourceManager.GetString("accountMailingAddressPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Only used when printing your logbook).
        /// </summary>
        internal static string accountMailingAddressPromptNote {
            get {
                return ResourceManager.GetString("accountMailingAddressPromptNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information successfully updated.
        /// </summary>
        internal static string accountPersonalInfoSuccess {
            get {
                return ResourceManager.GetString("accountPersonalInfoSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you leave this blank, your first name will be used.
        /// </summary>
        internal static string accountPreferredGreetingNote {
            get {
                return ResourceManager.GetString("accountPreferredGreetingNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred informal/short name.
        /// </summary>
        internal static string accountPreferredGreetingPrompt {
            get {
                return ResourceManager.GetString("accountPreferredGreetingPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (First Name).
        /// </summary>
        internal static string accountPreferredGreetingWatermark {
            get {
                return ResourceManager.GetString("accountPreferredGreetingWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype Email.
        /// </summary>
        internal static string accountRetypeEmailPrompt {
            get {
                return ResourceManager.GetString("accountRetypeEmailPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Account is now unlocked.
        /// </summary>
        internal static string AccountUnlockedSubject {
            get {
                return ResourceManager.GetString("AccountUnlockedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That link has expired, please use a new one..
        /// </summary>
        internal static string accountVerifyEmailExpired {
            get {
                return ResourceManager.GetString("accountVerifyEmailExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify email address.
        /// </summary>
        internal static string accountVerifyEmailPrompt {
            get {
                return ResourceManager.GetString("accountVerifyEmailPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message sent.  Please check your inbox..
        /// </summary>
        internal static string accountVerifyEmailSent {
            get {
                return ResourceManager.GetString("accountVerifyEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email has been verified.
        /// </summary>
        internal static string accountVerifyEmailValid {
            get {
                return ResourceManager.GetString("accountVerifyEmailValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something is wrong with the link you clicked.  Please try verification again..
        /// </summary>
        internal static string accountVerifyInvalid {
            get {
                return ResourceManager.GetString("accountVerifyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify your email on %APP_NAME%.
        /// </summary>
        internal static string accountVerifySubject {
            get {
                return ResourceManager.GetString("accountVerifySubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email {0} has been validated.  Thank-you..
        /// </summary>
        internal static string accountVerifyValidated {
            get {
                return ResourceManager.GetString("accountVerifyValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To verify your address, an email with a unique link will be sent to you.  By clicking on the link, you demonstrate your ability to receive messages at that address.  Verification is optional, but can help ensure that you can do things like password resets.
        /// </summary>
        internal static string accountVerifyWhy {
            get {
                return ResourceManager.GetString("accountVerifyWhy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage the aircraft that you fly, and add new models to the system.  Define new models of aircraft.  Or create a flying club if you share aircraft with others!.
        /// </summary>
        internal static string appDescriptionAircraft {
            get {
                return ResourceManager.GetString("appDescriptionAircraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View flight routes, see airports that you’ve visited, add missing airports.  Try your skills at identifying airports from satellite imagery.
        /// </summary>
        internal static string appDescriptionAirports {
            get {
                return ResourceManager.GetString("appDescriptionAirports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create or import your flights and see your currency and totals, and do deeper analysis. Download your logbook to a spreadsheet, or print your logbook.
        /// </summary>
        internal static string appDescriptionLogbook {
            get {
                return ResourceManager.GetString("appDescriptionLogbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create custom currency rules or deadlines, link to cloud storage and airline scheduling systems.
        /// </summary>
        internal static string appDescriptionProfile {
            get {
                return ResourceManager.GetString("appDescriptionProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track progress towards ratings, record endorsements, and manage relationships with students and instructors.  Earn badges for flying achievements!.
        /// </summary>
        internal static string appDescriptionTraining {
            get {
                return ResourceManager.GetString("appDescriptionTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorize %APP_NAME% to save backups to your Box account.
        /// </summary>
        internal static string AuthorizeBox {
            get {
                return ResourceManager.GetString("AuthorizeBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorize %APP_NAME% to work with CloudAhoy.
        /// </summary>
        internal static string AuthorizeCloudAhoy {
            get {
                return ResourceManager.GetString("AuthorizeCloudAhoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorize %APP_NAME% to save backups to your Dropbox account.
        /// </summary>
        internal static string AuthorizeDropbox {
            get {
                return ResourceManager.GetString("AuthorizeDropbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorize %APP_NAME% to work with FlySto.
        /// </summary>
        internal static string AuthorizeFlySto {
            get {
                return ResourceManager.GetString("AuthorizeFlySto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorize %APP_NAME% to save backups to your Google Drive account.
        /// </summary>
        internal static string AuthorizeGDrive {
            get {
                return ResourceManager.GetString("AuthorizeGDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorize %APP_NAME% to save backups to your OneDrive account.
        /// </summary>
        internal static string AuthorizeOneDrive {
            get {
                return ResourceManager.GetString("AuthorizeOneDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has changed since this authorization was issued.  Please sign out and in again with the new password..
        /// </summary>
        internal static string AuthTokenExpiredPassword {
            get {
                return ResourceManager.GetString("AuthTokenExpiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add BasicMed event.
        /// </summary>
        internal static string BasicMedAddEvent {
            get {
                return ResourceManager.GetString("BasicMedAddEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Click to record a BasicMed event).
        /// </summary>
        internal static string BasicMedAddEventPrompt {
            get {
                return ResourceManager.GetString("BasicMedAddEventPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload a photo or PDF record of your course completion or physician checklist.
        /// </summary>
        internal static string BasicMedAttachDocumentation {
            get {
                return ResourceManager.GetString("BasicMedAttachDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this record?  It cannot be undone..
        /// </summary>
        internal static string BasicMedConfirmDelete {
            get {
                return ResourceManager.GetString("BasicMedConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Due (BasicMed).
        /// </summary>
        internal static string BasicMedCurrencyTitle {
            get {
                return ResourceManager.GetString("BasicMedCurrencyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes this record.
        /// </summary>
        internal static string BasicMedDeleteTooltip {
            get {
                return ResourceManager.GetString("BasicMedDeleteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under BasicMed, you can do some types of flying without a current medical certificate if you meet a set of conditions, including (among others) the following (see 14 CFR 61.23 for more details):.
        /// </summary>
        internal static string BasicMedDescription {
            get {
                return ResourceManager.GetString("BasicMedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have held a valid FAA medical at some point since July 15, 2006 (be sure to enter this, even if expired).  If you enter a date of a medical certificate it is assumed to meet this requirement..
        /// </summary>
        internal static string BasicMedDescriptionA {
            get {
                return ResourceManager.GetString("BasicMedDescriptionA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have taken a course on aero-medical issues within the prior 24 calendar months.
        /// </summary>
        internal static string BasicMedDescriptionB {
            get {
                return ResourceManager.GetString("BasicMedDescriptionB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have visited a state-licensed physician and completed a checklist within the prior 4 years.  .
        /// </summary>
        internal static string BasicMedDescriptionC {
            get {
                return ResourceManager.GetString("BasicMedDescriptionC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This date is in the future.
        /// </summary>
        internal static string BasicMedErrEventInFuture {
            get {
                return ResourceManager.GetString("BasicMedErrEventInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This date is from before BasicMed went into effect.
        /// </summary>
        internal static string BasicMedErrEventTooFarBack {
            get {
                return ResourceManager.GetString("BasicMedErrEventTooFarBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need an FAA Medical dated on or after July 15, 2006.
        /// </summary>
        internal static string BasicMedErrMedicalNotFound {
            get {
                return ResourceManager.GetString("BasicMedErrMedicalNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a date.
        /// </summary>
        internal static string BasicMedErrNoDate {
            get {
                return ResourceManager.GetString("BasicMedErrNoDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to take a medical factors course.
        /// </summary>
        internal static string BasicMedErrNoMedicalCourseWithin2Years {
            get {
                return ResourceManager.GetString("BasicMedErrNoMedicalCourseWithin2Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need a visit to a physician.
        /// </summary>
        internal static string BasicMedErrNoPhysicalWithin4Years {
            get {
                return ResourceManager.GetString("BasicMedErrNoPhysicalWithin4Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity:.
        /// </summary>
        internal static string BasicMedEventActivity {
            get {
                return ResourceManager.GetString("BasicMedEventActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string BasicMedEventDate {
            get {
                return ResourceManager.GetString("BasicMedEventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes:.
        /// </summary>
        internal static string BasicMedEventDescription {
            get {
                return ResourceManager.GetString("BasicMedEventDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid until: .
        /// </summary>
        internal static string BasicMedExpiration {
            get {
                return ResourceManager.GetString("BasicMedExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAA BasicMed.
        /// </summary>
        internal static string BasicMedHeader {
            get {
                return ResourceManager.GetString("BasicMedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed medical course.
        /// </summary>
        internal static string BasicMedMedicalCourse {
            get {
                return ResourceManager.GetString("BasicMedMedicalCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not entered any courses or physician visits.
        /// </summary>
        internal static string BasicMedNoEvents {
            get {
                return ResourceManager.GetString("BasicMedNoEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visited Physician.
        /// </summary>
        internal static string BasicMedPhysicianVisit {
            get {
                return ResourceManager.GetString("BasicMedPhysicianVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BFR entered via Profile.
        /// </summary>
        internal static string BFRFromProfile {
            get {
                return ResourceManager.GetString("BFRFromProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can bulk delete unused aircraft, flights, or your entire account. .
        /// </summary>
        internal static string BigRedButtonsHeader {
            get {
                return ResourceManager.GetString("BigRedButtonsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have authorized %APP_NAME% to save backups to your Box account..
        /// </summary>
        internal static string BoxIsAuthed {
            get {
                return ResourceManager.GetString("BoxIsAuthed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (unknown).
        /// </summary>
        internal static string CFIExpirationUnknown {
            get {
                return ResourceManager.GetString("CFIExpirationUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CFI/CFII/GI Certificate: {0} (Expiration: {1}).
        /// </summary>
        internal static string CFILicenseTemplate {
            get {
                return ResourceManager.GetString("CFILicenseTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change name and email.
        /// </summary>
        internal static string ChangeNameEmail {
            get {
                return ResourceManager.GetString("ChangeNameEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your question/answer.
        /// </summary>
        internal static string ChangeQA {
            get {
                return ResourceManager.GetString("ChangeQA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have authorized %APP_NAME% to work with CloudAhoy.
        /// </summary>
        internal static string CloudAhoyIsAuthed {
            get {
                return ResourceManager.GetString("CloudAhoyIsAuthed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth: {0:d}.
        /// </summary>
        internal static string dateOfBirthFormat {
            get {
                return ResourceManager.GetString("dateOfBirthFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De-authorize %APP_NAME% to save backups to your Box account.
        /// </summary>
        internal static string DeAuthBox {
            get {
                return ResourceManager.GetString("DeAuthBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deauthorize %APP_NAME% on CloudAhoy.
        /// </summary>
        internal static string DeAuthCloudAhoy {
            get {
                return ResourceManager.GetString("DeAuthCloudAhoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De-authorize %APP_NAME% to save backups to your Dropbox account.
        /// </summary>
        internal static string DeAuthDropbox {
            get {
                return ResourceManager.GetString("DeAuthDropbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deauthorize %APP_NAME% on FlySto.
        /// </summary>
        internal static string DeAuthFlySto {
            get {
                return ResourceManager.GetString("DeAuthFlySto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deauthorize %APP_NAME% to save backups to your Google Drive account.
        /// </summary>
        internal static string DeAuthGDrive {
            get {
                return ResourceManager.GetString("DeAuthGDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deauthorize %APP_NAME% to save backups to your OneDrive account.
        /// </summary>
        internal static string DeAuthOneDrive {
            get {
                return ResourceManager.GetString("DeAuthOneDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have authorized %APP_NAME% to save backups to your Dropbox account..
        /// </summary>
        internal static string DropboxIsAuthed {
            get {
                return ResourceManager.GetString("DropboxIsAuthed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this instructor?.
        /// </summary>
        internal static string EditProfileDeleteCFIConfirmation {
            get {
                return ResourceManager.GetString("EditProfileDeleteCFIConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this instructor.
        /// </summary>
        internal static string EditProfileDeleteCFITooltip {
            get {
                return ResourceManager.GetString("EditProfileDeleteCFITooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this student?.
        /// </summary>
        internal static string EditProfileDeleteStudentConfirmation {
            get {
                return ResourceManager.GetString("EditProfileDeleteStudentConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this student.
        /// </summary>
        internal static string EditProfileDeleteStudentTooltip {
            get {
                return ResourceManager.GetString("EditProfileDeleteStudentTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile for {0}.
        /// </summary>
        internal static string EditProfileHeader {
            get {
                return ResourceManager.GetString("EditProfileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A request has been sent to {0}.  Their name will appear here when they accept your invitation.&lt;br /&gt;.
        /// </summary>
        internal static string EditProfileRequestHasBeenSent {
            get {
                return ResourceManager.GetString("EditProfileRequestHasBeenSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail Address Change Notification.
        /// </summary>
        internal static string EmailChangedSubjectLine {
            get {
                return ResourceManager.GetString("EmailChangedSubjectLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or as needed when currency expires or gets close to expiration.
        /// </summary>
        internal static string EmailCurrencyExpiration {
            get {
                return ResourceManager.GetString("EmailCurrencyExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support %APP_NAME% for US$15 to get this feature for a year!.
        /// </summary>
        internal static string EmailCurrencyExpirationPromotion {
            get {
                return ResourceManager.GetString("EmailCurrencyExpirationPromotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have flying currency that has expired or is expiring soon.
        /// </summary>
        internal static string EmailCurrencyExpiringMailSubject {
            get {
                return ResourceManager.GetString("EmailCurrencyExpiringMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your currency as of {0}.
        /// </summary>
        internal static string EmailCurrencyHeader {
            get {
                return ResourceManager.GetString("EmailCurrencyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency (Weekly).
        /// </summary>
        internal static string EmailCurrencyName {
            get {
                return ResourceManager.GetString("EmailCurrencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your monthly flying report from {0}.
        /// </summary>
        internal static string EmailMonthlyMailIntro {
            get {
                return ResourceManager.GetString("EmailMonthlyMailIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totals &amp; Currency (Monthly).
        /// </summary>
        internal static string EmailMonthlyName {
            get {
                return ResourceManager.GetString("EmailMonthlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your flying totals for {0}.
        /// </summary>
        internal static string EmailMonthlySubject {
            get {
                return ResourceManager.GetString("EmailMonthlySubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your flying totals for {0} and a review of {1}!.
        /// </summary>
        internal static string EmailMonthlySubjectYearInReview {
            get {
                return ResourceManager.GetString("EmailMonthlySubjectYearInReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribe from all subscribed email..
        /// </summary>
        internal static string EmailQuickUnsubscribeLink {
            get {
                return ResourceManager.GetString("EmailQuickUnsubscribeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your totals as of {0}.
        /// </summary>
        internal static string EmailTotalsHeader {
            get {
                return ResourceManager.GetString("EmailTotalsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totals (Weekly).
        /// </summary>
        internal static string EmailTotalsName {
            get {
                return ResourceManager.GetString("EmailTotalsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totals for {0} {1}.
        /// </summary>
        internal static string EmailTotalsPriorMonthHeader {
            get {
                return ResourceManager.GetString("EmailTotalsPriorMonthHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your totals for all of {0}.
        /// </summary>
        internal static string EmailTotalsPriorYearHeader {
            get {
                return ResourceManager.GetString("EmailTotalsPriorYearHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your year-to-date totals for {0}.
        /// </summary>
        internal static string EmailTotalsYTDHeader {
            get {
                return ResourceManager.GetString("EmailTotalsYTDHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your weekly stats from {0}.
        /// </summary>
        internal static string EmailWeeklyMailIntro {
            get {
                return ResourceManager.GetString("EmailWeeklyMailIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your weekly flying status.
        /// </summary>
        internal static string EmailWeeklyMailSubject {
            get {
                return ResourceManager.GetString("EmailWeeklyMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to manage your email subscription settings..
        /// </summary>
        internal static string EmailWeeklyMailUnsubscribeLink {
            get {
                return ResourceManager.GetString("EmailWeeklyMailUnsubscribeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 7 days.
        /// </summary>
        internal static string EmailWeeklyTotalsLabel {
            get {
                return ResourceManager.GetString("EmailWeeklyTotalsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happy New Year!  You can find a review of your flying for the whole year last year below.  Or, you can view a more comprehensive review of your flying year to date and share it with your friends!.
        /// </summary>
        internal static string EmailYearInReviewAnnual {
            get {
                return ResourceManager.GetString("EmailYearInReviewAnnual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View a review of your flying year to date and share it with your friends!.
        /// </summary>
        internal static string EmailYearInReviewEndOfYear {
            get {
                return ResourceManager.GetString("EmailYearInReviewEndOfYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Year in Review.
        /// </summary>
        internal static string EmailYearInReviewHeader {
            get {
                return ResourceManager.GetString("EmailYearInReviewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review your {0} flights.
        /// </summary>
        internal static string EmailYearInReviewVisit {
            get {
                return ResourceManager.GetString("EmailYearInReviewVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can issue an endorsement to a student, or record an endorsement that you have given to a student off-line.
        /// </summary>
        internal static string EndorsementDisclaimer {
            get {
                return ResourceManager.GetString("EndorsementDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let us know what we should add..
        /// </summary>
        internal static string EndorsementRequest {
            get {
                return ResourceManager.GetString("EndorsementRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t see a template you need?.
        /// </summary>
        internal static string EndorsementRequestPrompt {
            get {
                return ResourceManager.GetString("EndorsementRequestPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Students.
        /// </summary>
        internal static string EndorsementReturnToProfile {
            get {
                return ResourceManager.GetString("EndorsementReturnToProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endorsements you&apos;ve given to {0}:.
        /// </summary>
        internal static string EndorsementsExistingEndorsementHeader {
            get {
                return ResourceManager.GetString("EndorsementsExistingEndorsementHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endorsements for {0}.
        /// </summary>
        internal static string EndorsementsHeader {
            get {
                return ResourceManager.GetString("EndorsementsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New endorsement for {0}:.
        /// </summary>
        internal static string EndorsementsNewEndorsementHeader {
            get {
                return ResourceManager.GetString("EndorsementsNewEndorsementHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other (not from you) endorsements for {0}:.
        /// </summary>
        internal static string EndorsementsNotOwnedEndorsementHeader {
            get {
                return ResourceManager.GetString("EndorsementsNotOwnedEndorsementHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type your e-mail twice (avoids typos)..
        /// </summary>
        internal static string err2ndEmailRequired {
            get {
                return ResourceManager.GetString("err2ndEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security answer is too long..
        /// </summary>
        internal static string errAnswerTooLong {
            get {
                return ResourceManager.GetString("errAnswerTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be between 8 and 48 characters long..
        /// </summary>
        internal static string errBadPasswordLength {
            get {
                return ResourceManager.GetString("errBadPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password supplied; you must provide your current password in order to change it..
        /// </summary>
        internal static string errBadPasswordToChange {
            get {
                return ResourceManager.GetString("errBadPasswordToChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password failed..
        /// </summary>
        internal static string errChangePasswordFailed {
            get {
                return ResourceManager.GetString("errChangePasswordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change question/answer failed..
        /// </summary>
        internal static string errChangeQandAFailed {
            get {
                return ResourceManager.GetString("errChangeQandAFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is already used for an account..
        /// </summary>
        internal static string errEmailInUse {
            get {
                return ResourceManager.GetString("errEmailInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That email address is already in use by another account.
        /// </summary>
        internal static string errEmailInUse2 {
            get {
                return ResourceManager.GetString("errEmailInUse2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email address is required.
        /// </summary>
        internal static string errEmailMissing {
            get {
                return ResourceManager.GetString("errEmailMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address.
        /// </summary>
        internal static string errEmailRequired {
            get {
                return ResourceManager.GetString("errEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured creating the account: {0}.
        /// </summary>
        internal static string errGenericCreateAccountError {
            get {
                return ResourceManager.GetString("errGenericCreateAccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured saving the account: {0}.
        /// </summary>
        internal static string errGenericUpdateError {
            get {
                return ResourceManager.GetString("errGenericUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password.
        /// </summary>
        internal static string errIncorrectPassword {
            get {
                return ResourceManager.GetString("errIncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid answer..
        /// </summary>
        internal static string errInvalidAnswer {
            get {
                return ResourceManager.GetString("errInvalidAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; does not appear to be a valid email address.
        /// </summary>
        internal static string errInvalidEmail {
            get {
                return ResourceManager.GetString("errInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid password.
        /// </summary>
        internal static string errInvalidPassword {
            get {
                return ResourceManager.GetString("errInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid question.
        /// </summary>
        internal static string errInvalidQuestion {
            get {
                return ResourceManager.GetString("errInvalidQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change your secret question and answer, you must type BOTH a new question and a new answer.
        /// </summary>
        internal static string errNeedBothQandA {
            get {
                return ResourceManager.GetString("errNeedBothQandA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a security answer..
        /// </summary>
        internal static string errNoAnswer {
            get {
                return ResourceManager.GetString("errNoAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have a CFI/CFII/GI certificate number in your profile in order to endorse students..
        /// </summary>
        internal static string errNoCFICertificate {
            get {
                return ResourceManager.GetString("errNoCFICertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide an expiration date for your CFI/CFII/GI certificate in your profile in order to endorse students..
        /// </summary>
        internal static string errNoCFIExpiration {
            get {
                return ResourceManager.GetString("errNoCFIExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a password..
        /// </summary>
        internal static string errNoPassword {
            get {
                return ResourceManager.GetString("errNoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a security question..
        /// </summary>
        internal static string errNoQuestion {
            get {
                return ResourceManager.GetString("errNoQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to endorse this user.  Please establish a student/instructor relationship first..
        /// </summary>
        internal static string errNotAuthorizedToEndorse {
            get {
                return ResourceManager.GetString("errNotAuthorizedToEndorse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not configured for Box.  Please set this up in your preferences (under Profile).
        /// </summary>
        internal static string errNotConfiguredBox {
            get {
                return ResourceManager.GetString("errNotConfiguredBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not configured for Dropbox.  Please set this up in your preferences (under Profile).
        /// </summary>
        internal static string errNotConfiguredDropBox {
            get {
                return ResourceManager.GetString("errNotConfiguredDropBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not configured for GoogleDrive.  Please set this up in your preferences (under Profile).
        /// </summary>
        internal static string errNotConfiguredGoogleDrive {
            get {
                return ResourceManager.GetString("errNotConfiguredGoogleDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not configured for OneDrive.  Please set this up in your preferences (under Profile).
        /// </summary>
        internal static string errNotConfiguredOneDrive {
            get {
                return ResourceManager.GetString("errNotConfiguredOneDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user specified.
        /// </summary>
        internal static string errNoUserSpecified {
            get {
                return ResourceManager.GetString("errNoUserSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must successfully type your new password twice.
        /// </summary>
        internal static string errPasswordsDontMatch {
            get {
                return ResourceManager.GetString("errPasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type a new secret question and answer.
        /// </summary>
        internal static string errPleaseTypeNewQandA {
            get {
                return ResourceManager.GetString("errPleaseTypeNewQandA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security question is too long..
        /// </summary>
        internal static string errQuestionTooLong {
            get {
                return ResourceManager.GetString("errQuestionTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No email address was provided..
        /// </summary>
        internal static string errUnsubscribeNoEmail {
            get {
                return ResourceManager.GetString("errUnsubscribeNoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified email address was not found..
        /// </summary>
        internal static string errUnsubscribeNotFound {
            get {
                return ResourceManager.GetString("errUnsubscribeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have authorized %APP_NAME% to work with FlySto.
        /// </summary>
        internal static string FlyStoIsAuthed {
            get {
                return ResourceManager.GetString("FlyStoIsAuthed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have authorized %APP_NAME% to save backups to your Google Drive account..
        /// </summary>
        internal static string GDriveIsAuthed {
            get {
                return ResourceManager.GetString("GDriveIsAuthed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The most popular FREE logbook for pilots worldwide, created by pilots, for pilots.
        /// </summary>
        internal static string HomePageMostPopular {
            get {
                return ResourceManager.GetString("HomePageMostPopular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add flights (and images!) to your logbook from a browser or iOS/Android apps.  Sign flights and track endorsements.  Great for general aviation, airline, military, and even drone pilots!.
        /// </summary>
        internal static string homePromoAreaDesc1 {
            get {
                return ResourceManager.GetString("homePromoAreaDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View up-to-date totals, 8710 forms, track your progress towards ratings..
        /// </summary>
        internal static string homePromoAreaDesc2 {
            get {
                return ResourceManager.GetString("homePromoAreaDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track currency (FAA, EASA, others), including medicals flight reviews, duty periods, and maintenance on your aircraft.  Even create your own currency rules!.
        /// </summary>
        internal static string homePromoAreaDesc3 {
            get {
                return ResourceManager.GetString("homePromoAreaDesc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slice and dice your flying by time or aircraft type, see where you&apos;ve flown, and view trends..
        /// </summary>
        internal static string homePromoAreaDesc4 {
            get {
                return ResourceManager.GetString("homePromoAreaDesc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safely and securely share your logbook with instructor, flight schools, employers, or other pilots, or choose from a wide variety of print/PDF layouts..
        /// </summary>
        internal static string homePromoAreaDesc5 {
            get {
                return ResourceManager.GetString("homePromoAreaDesc5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access your logbook securely from any device anywhere, backup to cloud storage providers, push flights to debriefing services, or pull schedules from airline scheduling systems..
        /// </summary>
        internal static string homePromoAreaDesc6 {
            get {
                return ResourceManager.GetString("homePromoAreaDesc6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Flight Logging.
        /// </summary>
        internal static string homePromoAreaHeader1 {
            get {
                return ResourceManager.GetString("homePromoAreaHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powerful Reporting.
        /// </summary>
        internal static string homePromoAreaHeader2 {
            get {
                return ResourceManager.GetString("homePromoAreaHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency and Compliance.
        /// </summary>
        internal static string homePromoAreaHeader3 {
            get {
                return ResourceManager.GetString("homePromoAreaHeader3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytics and Ratings.
        /// </summary>
        internal static string homePromoAreaHeader4 {
            get {
                return ResourceManager.GetString("homePromoAreaHeader4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy Sharing.
        /// </summary>
        internal static string homePromoAreaHeader5 {
            get {
                return ResourceManager.GetString("homePromoAreaHeader5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Connected.
        /// </summary>
        internal static string homePromoAreaHeader6 {
            get {
                return ResourceManager.GetString("homePromoAreaHeader6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Currency.
        /// </summary>
        internal static string HomePromoCurrencyHeader {
            get {
                return ResourceManager.GetString("HomePromoCurrencyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %APP_NAME% Feedback.
        /// </summary>
        internal static string HomePromoFeedbackHeader {
            get {
                return ResourceManager.GetString("HomePromoFeedbackHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting started is easy.  Here&apos;s how.
        /// </summary>
        internal static string HomePromoGetStartedHeader {
            get {
                return ResourceManager.GetString("HomePromoGetStartedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join 100,000+ pilots worldwide who trust their logbooks to %APP_NAME%.
        /// </summary>
        internal static string HomePromoJoinCommunity {
            get {
                return ResourceManager.GetString("HomePromoJoinCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why pilots choose %APP_NAME%.
        /// </summary>
        internal static string HomePromoKeyFeaturesHeader {
            get {
                return ResourceManager.GetString("HomePromoKeyFeaturesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more about %APP_NAME%.
        /// </summary>
        internal static string HomePromoLearnMore {
            get {
                return ResourceManager.GetString("HomePromoLearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up - it’s quick and free.
        /// </summary>
        internal static string HomePromoStep1 {
            get {
                return ResourceManager.GetString("HomePromoStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your aircraft (it’s probably already in the system!) or import your flights from another source.
        /// </summary>
        internal static string HomePromoStep2 {
            get {
                return ResourceManager.GetString("HomePromoStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter flights - you can use the web site, or the iOS/Android apps.
        /// </summary>
        internal static string HomePromoStep3 {
            get {
                return ResourceManager.GetString("HomePromoStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus on your flying and let %APP_NAME% take care of tracking totals, currency, endorsements, and more!.
        /// </summary>
        internal static string HomePromoStep4 {
            get {
                return ResourceManager.GetString("HomePromoStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Totals.
        /// </summary>
        internal static string HomePromoTotalsHeader {
            get {
                return ResourceManager.GetString("HomePromoTotalsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to your logbook.
        /// </summary>
        internal static string HomePromoViewYourLogbook {
            get {
                return ResourceManager.GetString("HomePromoViewYourLogbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate: {0}.
        /// </summary>
        internal static string LicenseTemplate {
            get {
                return ResourceManager.GetString("LicenseTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %APP_NAME%  is the most popular digital pilot logbook worldwide that helps you track flights, stay current, and securely access your logbook from anywhere. Sign up in seconds and focus on your flying, not your logging!.
        /// </summary>
        internal static string MetaDescription {
            get {
                return ResourceManager.GetString("MetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password:.
        /// </summary>
        internal static string NewUserConfirmPasswordPrompt {
            get {
                return ResourceManager.GetString("NewUserConfirmPasswordPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        internal static string NewUserCreateAccount {
            get {
                return ResourceManager.GetString("NewUserCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account - it&apos;s Free!.
        /// </summary>
        internal static string NewUserCreateAccountPrompt {
            get {
                return ResourceManager.GetString("NewUserCreateAccountPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address you are trying to use is already in use.  If that is your email, please try signing in with it.  You can also perform a password reset if needed..
        /// </summary>
        internal static string NewUserEmailAlreadyInUse {
            get {
                return ResourceManager.GetString("NewUserEmailAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email and password.
        /// </summary>
        internal static string NewUserEmailAndPassHeader {
            get {
                return ResourceManager.GetString("NewUserEmailAndPassHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address uniquely identifies you, and enables a password reset if you forget it.  Don&apos;t worry, we don&apos;t share it!.
        /// </summary>
        internal static string NewUserEmailDisclaimer {
            get {
                return ResourceManager.GetString("NewUserEmailDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and its confirmation must match.
        /// </summary>
        internal static string NewUserErrPasswordMismatch {
            get {
                return ResourceManager.GetString("NewUserErrPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        internal static string NewUserExistingAccount {
            get {
                return ResourceManager.GetString("NewUserExistingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name (optional).
        /// </summary>
        internal static string NewUserNamePrompt {
            get {
                return ResourceManager.GetString("NewUserNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string NewUserPasswordPrompt {
            get {
                return ResourceManager.GetString("NewUserPasswordPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your account.
        /// </summary>
        internal static string NewUserPromptCreateAccountHeader {
            get {
                return ResourceManager.GetString("NewUserPromptCreateAccountHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Question and Answer.
        /// </summary>
        internal static string NewUserQAPrompt {
            get {
                return ResourceManager.GetString("NewUserQAPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Answer:.
        /// </summary>
        internal static string NewUserSecurityAnswerPrompt {
            get {
                return ResourceManager.GetString("NewUserSecurityAnswerPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Question:.
        /// </summary>
        internal static string NewUserSecurityQuestionPrompt {
            get {
                return ResourceManager.GetString("NewUserSecurityQuestionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have authorized %APP_NAME% to save backups to your OneDrive account..
        /// </summary>
        internal static string OneDriveIsAuthed {
            get {
                return ResourceManager.GetString("OneDriveIsAuthed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Notification of password change.
        /// </summary>
        internal static string PasswordChangedSubject {
            get {
                return ResourceManager.GetString("PasswordChangedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be between 8 and 48 characters.  A good password includes numbers, symbols, and both uppercase and lowercase letters.
        /// </summary>
        internal static string PasswordQualityHint {
            get {
                return ResourceManager.GetString("PasswordQualityHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &lt;div style=&quot;margin-left: auto; margin-right: auto; max-width: 600px&quot;&gt;
        ///    &lt;p style=&quot;text-align:center;&quot;&gt;&lt;img src=&quot;https://%APP_URL%%APP_LOGO%&quot; alt=&quot;%APP_NAME% Logo&quot; /&gt;&lt;/p&gt;
        ///    &lt;p&gt;Dear {0}:&lt;/p&gt;
        ///    &lt;p&gt;You currently have &lt;span style=&quot;font-weight:bold&quot;&gt;{1:#,###}&lt;/span&gt; pending flights in your account on %APP_NAME%&lt;/p&gt;
        ///
        ///    &lt;p&gt;
        ///        These flights are not yet part of your logbook, and as such they do not contribute towards your totals or your currency.  They are likely flights that resulted from an impo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PendingFlightsReminder {
            get {
                return ResourceManager.GetString("PendingFlightsReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have pending flights on %APP_NAME%.
        /// </summary>
        internal static string PendingFlightsReminderSubject {
            get {
                return ResourceManager.GetString("PendingFlightsReminderSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete my unused aircraft.
        /// </summary>
        internal static string ProfileBulkDeleteAircraft {
            get {
                return ResourceManager.GetString("ProfileBulkDeleteAircraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} aircraft deleted..
        /// </summary>
        internal static string ProfileBulkDeleteAircraftDeleted {
            get {
                return ResourceManager.GetString("ProfileBulkDeleteAircraftDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all unused aircraft from my account.
        /// </summary>
        internal static string ProfileBulkDeleteAircraftPrompt {
            get {
                return ResourceManager.GetString("ProfileBulkDeleteAircraftPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete ALL of your flights?  This CANNOT be undone!.
        /// </summary>
        internal static string ProfileBulkDeleteConfirm {
            get {
                return ResourceManager.GetString("ProfileBulkDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete my flights.
        /// </summary>
        internal static string ProfileBulkDeleteFlights {
            get {
                return ResourceManager.GetString("ProfileBulkDeleteFlights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to start over with your logbook, you can bulk-delete all of your flights from your account.  THIS CANNOT BE UNDONE!  Make sure you have a backup first!.
        /// </summary>
        internal static string ProfileBulkDeleteFlightsPrompt {
            get {
                return ResourceManager.GetString("ProfileBulkDeleteFlightsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due in {0:#,##0} day(s).
        /// </summary>
        internal static string ProfileCurrencyStatusClose {
            get {
                return ResourceManager.GetString("ProfileCurrencyStatusClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired {0:#,##0} day(s) ago.
        /// </summary>
        internal static string ProfileCurrencyStatusNotCurrent {
            get {
                return ResourceManager.GetString("ProfileCurrencyStatusNotCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close my account.
        /// </summary>
        internal static string ProfileDeleteAccount {
            get {
                return ResourceManager.GetString("ProfileDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close your account?  This CANNOT be undone!.
        /// </summary>
        internal static string ProfileDeleteAccountConfirm {
            get {
                return ResourceManager.GetString("ProfileDeleteAccountConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While we&apos;re sorry to see anybody go, you can close your account at any time.  THIS CANNOT BE UNDONE!  Make sure you have a backup first!.
        /// </summary>
        internal static string ProfileDeleteAccountPrompt {
            get {
                return ResourceManager.GetString("ProfileDeleteAccountPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your flights have been deleted..
        /// </summary>
        internal static string ProfileDeleteFlightsCompleted {
            get {
                return ResourceManager.GetString("ProfileDeleteFlightsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big Red Buttons.
        /// </summary>
        internal static string ProfileDeleteHeader {
            get {
                return ResourceManager.GetString("ProfileDeleteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificates.
        /// </summary>
        internal static string ProfilePilotInfoCertificates {
            get {
                return ResourceManager.GetString("ProfilePilotInfoCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Certificates.
        /// </summary>
        internal static string ProfilePilotInfoCertificatesUpdate {
            get {
                return ResourceManager.GetString("ProfilePilotInfoCertificatesUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate information successfully updated.
        /// </summary>
        internal static string ProfilePilotInfoCertificatesUpdated {
            get {
                return ResourceManager.GetString("ProfilePilotInfoCertificatesUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your junk mail folder.
        /// </summary>
        internal static string resetPassCheckJunk {
            get {
                return ResourceManager.GetString("resetPassCheckJunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password: Choose a new password.
        /// </summary>
        internal static string resetPassChooseNew {
            get {
                return ResourceManager.GetString("resetPassChooseNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the e-mail address associated with your account:.
        /// </summary>
        internal static string resetPassEmailPrompt {
            get {
                return ResourceManager.GetString("resetPassEmailPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail sent.
        /// </summary>
        internal static string resetPassEmailSent {
            get {
                return ResourceManager.GetString("resetPassEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you don&apos;t receive it momentarily....
        /// </summary>
        internal static string resetPassIfNoReceive {
            get {
                return ResourceManager.GetString("resetPassIfNoReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The answer must match EXACTLY, including capitalization, punctuation, and spaces..
        /// </summary>
        internal static string resetPassQANote {
            get {
                return ResourceManager.GetString("resetPassQANote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the answer to the following question, which you provided when you created your account.
        /// </summary>
        internal static string resetPassQAPrompt {
            get {
                return ResourceManager.GetString("resetPassQAPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your question:.
        /// </summary>
        internal static string resetPassQuestion {
            get {
                return ResourceManager.GetString("resetPassQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a password reset.
        /// </summary>
        internal static string resetPassSendEmail {
            get {
                return ResourceManager.GetString("resetPassSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string resetPassTitle {
            get {
                return ResourceManager.GetString("resetPassTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password: Verify Your Identity.
        /// </summary>
        internal static string resetPassVerify {
            get {
                return ResourceManager.GetString("resetPassVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Verify that the email address is the one you use for your account*.  For security, we don&apos;t tell you whether or not an account exists or whether a given email address is associated with an account..
        /// </summary>
        internal static string resetPassVerifyCorrectEmail {
            get {
                return ResourceManager.GetString("resetPassVerifyCorrectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Students.
        /// </summary>
        internal static string ReturnToProfile {
            get {
                return ResourceManager.GetString("ReturnToProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to logbook for student {0}.
        /// </summary>
        internal static string ReturnToStudent {
            get {
                return ResourceManager.GetString("ReturnToStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        internal static string saveChanges {
            get {
                return ResourceManager.GetString("saveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        internal static string SignInNewUserPrompt {
            get {
                return ResourceManager.GetString("SignInNewUserPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect code provided.
        /// </summary>
        internal static string TFACodeFailed {
            get {
                return ResourceManager.GetString("TFACodeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code successfully validated.
        /// </summary>
        internal static string TFACodeValidated {
            get {
                return ResourceManager.GetString("TFACodeValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn off 2-Factor Authentication for my account.
        /// </summary>
        internal static string TFADisable {
            get {
                return ResourceManager.GetString("TFADisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download an authenticator app from app to your iOS or Android device..
        /// </summary>
        internal static string TFADownloadGoogleAuthenticator {
            get {
                return ResourceManager.GetString("TFADownloadGoogleAuthenticator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add 2-Factor Authentication to my account.
        /// </summary>
        internal static string TFAEnable {
            get {
                return ResourceManager.GetString("TFAEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter 6-digit code.
        /// </summary>
        internal static string TFAEnterCodePrompt {
            get {
                return ResourceManager.GetString("TFAEnterCodePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code must be 6 digits.
        /// </summary>
        internal static string TFAErrCodeFormat {
            get {
                return ResourceManager.GetString("TFAErrCodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-Factor Authentication.
        /// </summary>
        internal static string TFAHeader {
            get {
                return ResourceManager.GetString("TFAHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-Factor Authentication is active for your account..
        /// </summary>
        internal static string TFAIsSetUp {
            get {
                return ResourceManager.GetString("TFAIsSetUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more....
        /// </summary>
        internal static string TFALearnMore {
            get {
                return ResourceManager.GetString("TFALearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-factor authentication (2FA) provides an additional layer of security for your account by requiring a second method in addition to your password to authenticate yourself, making it harder for a hacker to gain access to your account..
        /// </summary>
        internal static string TFAOverview {
            get {
                return ResourceManager.GetString("TFAOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because your account has 2-factor authentication turned on, we need to first verify that you are in fact you..
        /// </summary>
        internal static string TFARequired {
            get {
                return ResourceManager.GetString("TFARequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should also write down the secret key and keep it in a safe place SEPARATE from any other passwords, so that you can restore access in case you lose your device..
        /// </summary>
        internal static string TFASaveSecretKey {
            get {
                return ResourceManager.GetString("TFASaveSecretKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret Key: .
        /// </summary>
        internal static string TFASecretKeyPrompt {
            get {
                return ResourceManager.GetString("TFASecretKeyPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using the authenticator app, scan the QR code below with your device&apos;s camera, or enter the &quot;secret key&quot; directly. .
        /// </summary>
        internal static string TFATwoOptionsPrompt {
            get {
                return ResourceManager.GetString("TFATwoOptionsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %APP_NAME% uses an authentication app that you download to your phone/tablet, such as Google Authenticator or Microsoft Authenticator, for 2-factor authentication.  The app provides a time-limited code to enter after providing your password.  If you enable 2-factor authentication for your account, then you MUST have access to the app on your phone in order to sign in..
        /// </summary>
        internal static string TFAUseGA {
            get {
                return ResourceManager.GetString("TFAUseGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the authenticator app on your phone/tablet to get a current code..
        /// </summary>
        internal static string TFAUseYourApp {
            get {
                return ResourceManager.GetString("TFAUseYourApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate code.
        /// </summary>
        internal static string TFAValidateCode {
            get {
                return ResourceManager.GetString("TFAValidateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once you have scanned the QR code or entered the secret key, enter and verify the 6-digit password below:.
        /// </summary>
        internal static string TFAValidateCodePrompt {
            get {
                return ResourceManager.GetString("TFAValidateCodePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training for {0}.
        /// </summary>
        internal static string TrainingHeader {
            get {
                return ResourceManager.GetString("TrainingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribe.
        /// </summary>
        internal static string UnsubscribeHeader {
            get {
                return ResourceManager.GetString("UnsubscribeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All subscribed email for {0} has been cancelled..
        /// </summary>
        internal static string UnsubscribeSuccessful {
            get {
                return ResourceManager.GetString("UnsubscribeSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;%APP_NAME% is asking you to verify that you are the owner of the email address &lt;% email %&gt;.&lt;/p&gt;
        ///&lt;p&gt;
        ///    Please click on &lt;a href=&quot;&lt;% confirmaddress %&gt;&quot;&gt;this link&lt;/a&gt; to confirm your address.  This link is valid for one hour.
        ///&lt;/p&gt;
        ///.
        /// </summary>
        internal static string VerifyEmail {
            get {
                return ResourceManager.GetString("VerifyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to %APP_NAME%.
        /// </summary>
        internal static string WelcomeGeneric {
            get {
                return ResourceManager.GetString("WelcomeGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - The world&apos;s favorite free logbook.
        /// </summary>
        internal static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Free online logbook for pilots!.
        /// </summary>
        internal static string WelcomeTitleWithDescription {
            get {
                return ResourceManager.GetString("WelcomeTitleWithDescription", resourceCulture);
            }
        }
    }
}
