//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Totals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Totals() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Totals", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approach.
        /// </summary>
        internal static string Approach {
            get {
                return ResourceManager.GetString("Approach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approaches.
        /// </summary>
        internal static string Approaches {
            get {
                return ResourceManager.GetString("Approaches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CFI.
        /// </summary>
        internal static string CFI {
            get {
                return ResourceManager.GetString("CFI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex.
        /// </summary>
        internal static string Complex {
            get {
                return ResourceManager.GetString("Complex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross Country.
        /// </summary>
        internal static string CrossCountry {
            get {
                return ResourceManager.GetString("CrossCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string DayLanding {
            get {
                return ResourceManager.GetString("DayLanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dual.
        /// </summary>
        internal static string Dual {
            get {
                return ResourceManager.GetString("Dual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine Time.
        /// </summary>
        internal static string EngineTime {
            get {
                return ResourceManager.GetString("EngineTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight Time.
        /// </summary>
        internal static string FlightTime {
            get {
                return ResourceManager.GetString("FlightTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ground Simulator.
        /// </summary>
        internal static string Ground {
            get {
                return ResourceManager.GetString("Ground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :00.
        /// </summary>
        internal static string HiddenAlignment {
            get {
                return ResourceManager.GetString("HiddenAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Performance.
        /// </summary>
        internal static string HighPerf {
            get {
                return ResourceManager.GetString("HighPerf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hobbs.
        /// </summary>
        internal static string Hobbs {
            get {
                return ResourceManager.GetString("Hobbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMC.
        /// </summary>
        internal static string IMC {
            get {
                return ResourceManager.GetString("IMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landing.
        /// </summary>
        internal static string Landing {
            get {
                return ResourceManager.GetString("Landing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landings.
        /// </summary>
        internal static string Landings {
            get {
                return ResourceManager.GetString("Landings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide matching flights.
        /// </summary>
        internal static string lnkHideMatchingFlights {
            get {
                return ResourceManager.GetString("lnkHideMatchingFlights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show matching flights.
        /// </summary>
        internal static string lnkShowMatchingFlights {
            get {
                return ResourceManager.GetString("lnkShowMatchingFlights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night.
        /// </summary>
        internal static string Night {
            get {
                return ResourceManager.GetString("Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night.
        /// </summary>
        internal static string NightLanding {
            get {
                return ResourceManager.GetString("NightLanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No totals).
        /// </summary>
        internal static string NoTotals {
            get {
                return ResourceManager.GetString("NoTotals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIC.
        /// </summary>
        internal static string PIC {
            get {
                return ResourceManager.GetString("PIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIC/Total.
        /// </summary>
        internal static string PICTotal {
            get {
                return ResourceManager.GetString("PICTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retract.
        /// </summary>
        internal static string Retract {
            get {
                return ResourceManager.GetString("Retract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIC.
        /// </summary>
        internal static string SIC {
            get {
                return ResourceManager.GetString("SIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIC/Total.
        /// </summary>
        internal static string SICTotal {
            get {
                return ResourceManager.GetString("SICTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulated Instrument.
        /// </summary>
        internal static string SimIMC {
            get {
                return ResourceManager.GetString("SimIMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tailwheel.
        /// </summary>
        internal static string Tailwheel {
            get {
                return ResourceManager.GetString("Tailwheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Total for all].
        /// </summary>
        internal static string TotalForAllCatClass {
            get {
                return ResourceManager.GetString("TotalForAllCatClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times by aircraft features.
        /// </summary>
        internal static string TotalGroupCapabilities {
            get {
                return ResourceManager.GetString("TotalGroupCapabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totals by Category/Class.
        /// </summary>
        internal static string TotalGroupCategoryClass {
            get {
                return ResourceManager.GetString("TotalGroupCategoryClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Logbook Times.
        /// </summary>
        internal static string TotalGroupCoreFields {
            get {
                return ResourceManager.GetString("TotalGroupCoreFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totals by ICAO code.
        /// </summary>
        internal static string TotalGroupICAO {
            get {
                return ResourceManager.GetString("TotalGroupICAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totals by Model.
        /// </summary>
        internal static string TotalGroupModel {
            get {
                return ResourceManager.GetString("TotalGroupModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Totals.
        /// </summary>
        internal static string TotalGroupProperties {
            get {
                return ResourceManager.GetString("TotalGroupProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Total Flight Time.
        /// </summary>
        internal static string TotalGroupTotal {
            get {
                return ResourceManager.GetString("TotalGroupTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show as flat list.
        /// </summary>
        internal static string TotalsModeFlat {
            get {
                return ResourceManager.GetString("TotalsModeFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show grouped.
        /// </summary>
        internal static string TotalsModeGrouped {
            get {
                return ResourceManager.GetString("TotalsModeGrouped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Time.
        /// </summary>
        internal static string TotalTime {
            get {
                return ResourceManager.GetString("TotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turbine.
        /// </summary>
        internal static string Turbine {
            get {
                return ResourceManager.GetString("Turbine", resourceCulture);
            }
        }
    }
}
