CREATE TABLE `isocodes` (
  `Region` varchar(255) NOT NULL COMMENT 'Region name - can be country/region (e.g., "Greenland" or "United States") or secondary ("Quebec")',
  `ISO` varchar(3) NOT NULL COMMENT '2- or 3- letter ISO code',
  `Level` int NOT NULL COMMENT '0 for top level ("United States"), 1 for secondary ("California")',
  UNIQUE KEY `unique` (`Region`,`ISO`,`Level`),
  KEY `main` (`Region`,`ISO`,`Level`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

/*
-- Query: select * from isocodes
-- Date: 2023-07-09 10:55
*/
INSERT INTO `isocodes` (`Region`,`ISO`,`Level`) VALUES ('Afghanistan','AFG',0),
('Akrotiri Sovereign Base Area','GBR',0),
('Åland Islands','ALA',0),
('Albania','ALB',0),
('Algeria','DZA',0),
('Andorra','AND',0),
('Angola','AGO',0),
('Anguilla','AIA',0),
('Antarctica','ATA',0),
('Antigua and Barbuda','ATG',0),
('Argentina','ARG',0),
('Armenia','ARM',0),
('Australia','AUS',0),
('Austria','AUT',0),
('Azerbaijan','AZE',0),
('Bahrain','BHR',0),
('Bangladesh','BGD',0),
('Barbados','BRB',0),
('Belarus','BLR',0),
('Belgium','BEL',0),
('Belize','BLZ',0),
('Benin','BEN',0),
('Bermuda','BMU',0),
('Bhutan','BTN',0),
('Bolivia','BOL',0),
('Bosnia and Herzegovina','BIH',0),
('Botswana','BWA',0),
('Brazil','BRA',0),
('British Virgin Islands','VGB',0),
('Brunei','BRN',0),
('Bulgaria','BGR',0),
('Burkina Faso','BFA',0),
('Burundi','BDI',0),
('Cambodia','KHM',0),
('Cameroon','CMR',0),
('Canada','CAN',0),
('Cape Verde','CPV',0),
('Caribbean Netherlands','NLD',0),
('Cayman Islands','CYM',0),
('Central African Republic','CAF',0),
('Chad','TCD',0),
('Chile','CHL',0),
('China','CHN',0),
('Colombia','COL',0),
('Comoros','COM',0),
('Cook Islands','COK',0),
('Costa Rica','CRI',0),
('Croatia','HRV',0),
('Cuba','CUB',0),
('Cuba (US Leased)','USA',0),
('Cyprus','CYP',0),
('Czech Republic','CZE',0),
('Democratic Republic of the Congo','COD',0),
('Denmark','DNK',0),
('Dhekelia Sovereign Base Area','GBR',0),
('Djibouti','DJI',0),
('Dominica','DMA',0),
('Dominican Republic','DOM',0),
('East Timor','TLS',0),
('Ecuador','ECU',0),
('Egypt','EGY',0),
('El Salvador','SLV',0),
('Equatorial Guinea','GNQ',0),
('Eritrea','ERI',0),
('Estonia','EST',0),
('Ethiopia','ETH',0),
('Faroe Islands','FRO',0),
('Fiji','FJI',0),
('Finland','FIN',0),
('France','FRA',0),
('French Polynesia','PYF',0),
('Gabon','GAB',0),
('Gambia','GMB',0),
('Georgia','GEO',0),
('Germany','DEU',0),
('Ghana','GHA',0),
('Greece','GRC',0),
('Greenland','GRL',0),
('Grenada','GRD',0),
('Guatemala','GTM',0),
('Guernsey','GGY',0),
('Guinea','GIN',0),
('Guinea Bissau','GNB',0),
('Guyana','GUY',0),
('Haiti','HTI',0),
('Honduras','HND',0),
('Hong Kong S.A.R.','HKG',0),
('Hungary','HUN',0),
('Iceland','ISL',0),
('India','IND',0),
('Indian Ocean Territories','AUS',0),
('Indonesia','IDN',0),
('Iran','IRN',0),
('Iraq','IRQ',0),
('Ireland','IRL',0),
('Isle of Man','IMN',0),
('Israel','ISR',0),
('Italy','ITA',0),
('Ivory Coast','CIV',0),
('Jamaica','JAM',0),
('Japan','JPN',0),
('Jersey','JEY',0),
('Jordan','JOR',0),
('Kazakhstan','KAZ',0),
('Kenya','KEN',0),
('Kiribati','KIR',0),
('Kosovo','',0),
('Kuwait','KWT',0),
('Kyrgyzstan','KGZ',0),
('Laos','LAO',0),
('Latvia','LVA',0),
('Lebanon','LBN',0),
('Lesotho','LSO',0),
('Liberia','LBR',0),
('Libya','LBY',0),
('Liechtenstein','LIE',0),
('Lithuania','LTU',0),
('Luxembourg','LUX',0),
('Macedonia','MKD',0),
('Madagascar','MDG',0),
('Malawi','MWI',0),
('Malaysia','MYS',0),
('Maldives','MDV',0),
('Mali','MLI',0),
('Malta','MLT',0),
('Marshall Islands','MHL',0),
('Mauritania','MRT',0),
('Mauritius','MUS',0),
('Mexico','MEX',0),
('Micronesia','FSM',0),
('Moldova','MDA',0),
('Monaco','MCO',0),
('Mongolia','MNG',0),
('Montenegro','MNE',0),
('Montserrat','MSR',0),
('Morocco','MAR',0),
('Mozambique','MOZ',0),
('Myanmar','MMR',0),
('Namibia','NAM',0),
('Nauru','NRU',0),
('Nepal','NPL',0),
('Netherlands','NLD',0),
('New Caledonia','NCL',0),
('New Zealand','NZL',0),
('Nicaragua','NIC',0),
('Niger','NER',0),
('Nigeria','NGA',0),
('Niue','NIU',0),
('Norfolk Island','NFK',0),
('North Korea','PRK',0),
('Northern Mariana Islands','MNP',0),
('Norway','NOR',0),
('Oman','OMN',0),
('Pakistan','PAK',0),
('Palau','PLW',0),
('Panama','PAN',0),
('Papua New Guinea','PNG',0),
('Paraguay','PRY',0),
('Peru','PER',0),
('Philippines','PHL',0),
('Poland','POL',0),
('Portugal','PRT',0),
('Puerto Rico','PRI',0),
('Qatar','QAT',0),
('Republic of Serbia','SRB',0),
('Republic of the Congo','COG',0),
('Romania','ROU',0),
('Russia','RUS',0),
('Rwanda','RWA',0),
('S. Sudan','SSD',0),
('Saint Barthélemy','BLM',0),
('Saint Helena','SHN',0),
('Saint Kitts and Nevis','KNA',0),
('Saint Lucia','LCA',0),
('Saint Martin','MAF',0),
('Saint Pierre and Miquelon','SPM',0),
('Saint Vincent and the Grenadines','VCT',0),
('Samoa','WSM',0),
('San Marino','SMR',0),
('Sao Tome and Principe','STP',0),
('Saudi Arabia','SAU',0),
('Senegal','SEN',0),
('Seychelles','SYC',0),
('Sierra Leone','SLE',0),
('Singapore','SGP',0),
('Slovakia','SVK',0),
('Slovenia','SVN',0),
('Solomon Islands','SLB',0),
('Somalia','SOM',0),
('Somalia/Somaliland','SOM',0),
('South Africa','ZAF',0),
('South Korea','KOR',0),
('Spain','ESP',0),
('Sri Lanka','LKA',0),
('Sudan','SDN',0),
('Suriname','SUR',0),
('Swaziland','SWZ',0),
('Sweden','SWE',0),
('Switzerland','CHE',0),
('Syria','SYR',0),
('Taiwan','TWN',0),
('Tajikistan','TJK',0),
('Thailand','THA',0),
('The Bahamas','BHS',0),
('Togo','TGO',0),
('Tonga','TON',0),
('Trinidad and Tobago','TTO',0),
('Tunisia','TUN',0),
('Turkey','TUR',0),
('Turkmenistan','TKM',0),
('Turks and Caicos Islands','TCA',0),
('Tuvalu','TUV',0),
('Uganda','UGA',0),
('Ukraine','UKR',0),
('United Arab Emirates','ARE',0),
('United Kingdom','GBR',0),
('United Republic of Tanzania','TZA',0),
('United States','USA',0),
('United States Minor Outlying Islands','UMI',0),
('United States Virgin Islands','VIR',0),
('Uruguay','URY',0),
('Uzbekistan','UZB',0),
('Vanuatu','VUT',0),
('Venezuela','VEN',0),
('Vietnam','VNM',0),
('Wallis and Futuna','WLF',0),
('Yemen','YEM',0),
('Zambia','ZMB',0),
('Zimbabwe','ZWE',0),
('Alabama', 'AL', 1),
('Alaska', 'AK', 1),
('American Samoa', 'AS', 1),
('Arizona', 'AZ', 1),
('Arkansas', 'AR', 1),
('California', 'CA', 1),
('Colorado', 'CO', 1),
('Connecticut', 'CT', 1),
('D.C.', 'DC', 1),
('Delaware', 'DE', 1),
('District Of Columbia', 'DC', 1),
('Federated States Of Micronesia', 'FM', 1),
('Florida', 'FL', 1),
('Georgia', 'GA', 1),
('Guam', 'GU', 1),
('Hawaii', 'HI', 1),
('Idaho', 'ID', 1),
('Illinois', 'IL', 1),
('Indiana', 'IN', 1),
('Iowa', 'IA', 1),
('Kansas', 'KS', 1),
('Kentucky', 'KY', 1),
('Louisiana', 'LA', 1),
('Maine', 'ME', 1),
('Marshall Islands', 'MH', 1),
('Maryland', 'MD', 1),
('Massachusetts', 'MA', 1),
('Michigan', 'MI', 1),
('Minnesota', 'MN', 1),
('Mississippi', 'MS', 1),
('Missouri', 'MO', 1),
('Montana', 'MT', 1),
('Nebraska', 'NE', 1),
('Nevada', 'NV', 1),
('New Hampshire', 'NH', 1),
('New Jersey', 'NJ', 1),
('New Mexico', 'NM', 1),
('New York', 'NY', 1),
('North Carolina', 'NC', 1),
('North Dakota', 'ND', 1),
('Northern Mariana Islands', 'MP', 1),
('Ohio', 'OH', 1),
('Oklahoma', 'OK', 1),
('Oregon', 'OR', 1),
('Palau', 'PW', 1),
('Pennsylvania', 'PA', 1),
('Puerto Rico', 'PR', 1),
('Rhode Island', 'RI', 1),
('South Carolina', 'SC', 1),
('South Dakota', 'SD', 1),
('Tennessee', 'TN', 1),
('Texas', 'TX', 1),
('Utah', 'UT', 1),
('Vermont', 'VT', 1),
('US Virgin Islands', 'VI', 1),
('Virgin Islands', 'VI', 1),
('Virginia', 'VA', 1),
('Washington', 'WA', 1),
('West Virginia', 'WV', 1),
('Wisconsin', 'WI', 1),
('Wyoming', 'WY', 1),
('Alberta', 'AB', 1),
('British Columbia', 'BC', 1),
('Manitoba', 'MB', 1),
('New Brunswick', 'NB', 1),
('Newfoundland and Labrador', 'NL', 1),
('Nova Scotia', 'NS', 1),
('Ontario', 'ON', 1),
('Prince Edward Island', 'PE', 1),
('Québec', 'QC', 1),
('Saskatchewan', 'SK', 1),
('Northwest Territories', 'NT', 1),
('Nunavut', 'NU', 1),
('Yukon', 'YT', 1),
('New South Wales', 'NSW', 1),
('Northern Territory', 'NT', 1),
('Queensland', 'QLD', 1),
('South Australia', 'SA', 1),
('Tasmania', 'TAS', 1),
('Victoria', 'VIC', 1),
('Western Australia', 'WA', 1);