//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AircraftSupport.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AircraftResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AircraftResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AircraftSupport.Properties.AircraftResources", typeof(AircraftResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Type: {1}).
        /// </summary>
        internal static string DisplayTemplateWithType {
            get {
                return ResourceManager.GetString("DisplayTemplateWithType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEP (Land).
        /// </summary>
        internal static string EASACategoryClassAMELP {
            get {
                return ResourceManager.GetString("EASACategoryClassAMELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MET (Land).
        /// </summary>
        internal static string EASACategoryClassAMELT {
            get {
                return ResourceManager.GetString("EASACategoryClassAMELT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEP (Sea).
        /// </summary>
        internal static string EASACategoryClassAMESP {
            get {
                return ResourceManager.GetString("EASACategoryClassAMESP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MET (Sea).
        /// </summary>
        internal static string EASACategoryClassAMEST {
            get {
                return ResourceManager.GetString("EASACategoryClassAMEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEP (Land).
        /// </summary>
        internal static string EASACategoryClassASELP {
            get {
                return ResourceManager.GetString("EASACategoryClassASELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET (Land).
        /// </summary>
        internal static string EASACategoryClassASELT {
            get {
                return ResourceManager.GetString("EASACategoryClassASELT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEP (Sea).
        /// </summary>
        internal static string EASACategoryClassASESP {
            get {
                return ResourceManager.GetString("EASACategoryClassASESP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET (Sea).
        /// </summary>
        internal static string EASACategoryClassASEST {
            get {
                return ResourceManager.GetString("EASACategoryClassASEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sailplane.
        /// </summary>
        internal static string EASACategoryClassGlider {
            get {
                return ResourceManager.GetString("EASACategoryClassGlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor Glider.
        /// </summary>
        internal static string EASACategoryClassMotorGlider {
            get {
                return ResourceManager.GetString("EASACategoryClassMotorGlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilt Rotor.
        /// </summary>
        internal static string EASACategoryClassPoweredLift {
            get {
                return ResourceManager.GetString("EASACategoryClassPoweredLift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a model name.
        /// </summary>
        internal static string editMakeValModelNameRequired {
            get {
                return ResourceManager.GetString("editMakeValModelNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICAO/FAA codes may only be up to 4 alphanumeric characters.
        /// </summary>
        internal static string errInvalidICAO {
            get {
                return ResourceManager.GetString("errInvalidICAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a manufacturer from the list.  You can add one if needed..
        /// </summary>
        internal static string errManufacturerRequired {
            get {
                return ResourceManager.GetString("errManufacturerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission/Design/Series &apos;{0}&apos; is too long; please provide one that is fewer than 40 characters in length.
        /// </summary>
        internal static string errMDSTooLong {
            get {
                return ResourceManager.GetString("errMDSTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving make/model: {0}.
        /// </summary>
        internal static string errSaveMakeFailed {
            get {
                return ResourceManager.GetString("errSaveMakeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving manufacturer - {0}\r\n{1}.
        /// </summary>
        internal static string errSaveManufacturerFailed {
            get {
                return ResourceManager.GetString("errSaveManufacturerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model is certified for single-pilot operations, but it isn&apos;t turbine or doesn&apos;t require a type rating.
        /// </summary>
        internal static string errSinglePilotButNotTypeRated {
            get {
                return ResourceManager.GetString("errSinglePilotButNotTypeRated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a yes/no field.  If a type rating is required to fly aircraft of this model, please enter it here.  You can use the provided link to find FAA-specified type designators, or look up other similar models to find the correct type rating requirement to use..
        /// </summary>
        internal static string errYesNotValidType {
            get {
                return ResourceManager.GetString("errYesNotValidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flaps.
        /// </summary>
        internal static string HasFlaps {
            get {
                return ResourceManager.GetString("HasFlaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (ICAO: {0}).
        /// </summary>
        internal static string ICAOTemplate {
            get {
                return ResourceManager.GetString("ICAOTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certified for Single Pilot Operations.
        /// </summary>
        internal static string IsCertifiedSinglePilot {
            get {
                return ResourceManager.GetString("IsCertifiedSinglePilot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex.
        /// </summary>
        internal static string IsComplex {
            get {
                return ResourceManager.GetString("IsComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controllable Pitch Prop.
        /// </summary>
        internal static string IsConstantProp {
            get {
                return ResourceManager.GetString("IsConstantProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric.
        /// </summary>
        internal static string IsElectric {
            get {
                return ResourceManager.GetString("IsElectric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glass Cockpit.
        /// </summary>
        internal static string IsGlass {
            get {
                return ResourceManager.GetString("IsGlass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Performance.
        /// </summary>
        internal static string IsHighPerf {
            get {
                return ResourceManager.GetString("IsHighPerf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jet.
        /// </summary>
        internal static string IsJet {
            get {
                return ResourceManager.GetString("IsJet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Performance Until Aug 1997.
        /// </summary>
        internal static string IsLegacyHighPerf {
            get {
                return ResourceManager.GetString("IsLegacyHighPerf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-engine Helicopter.
        /// </summary>
        internal static string IsMultiHelicopter {
            get {
                return ResourceManager.GetString("IsMultiHelicopter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retractable Gear.
        /// </summary>
        internal static string IsRetract {
            get {
                return ResourceManager.GetString("IsRetract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technically Advanced Airplane (TAA).
        /// </summary>
        internal static string IsTAA {
            get {
                return ResourceManager.GetString("IsTAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tailwheel.
        /// </summary>
        internal static string IsTailwheel {
            get {
                return ResourceManager.GetString("IsTailwheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor Glider/TMG.
        /// </summary>
        internal static string IsTMG {
            get {
                return ResourceManager.GetString("IsTMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turbine.
        /// </summary>
        internal static string IsTurbine {
            get {
                return ResourceManager.GetString("IsTurbine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turboprop.
        /// </summary>
        internal static string IsTurboprop {
            get {
                return ResourceManager.GetString("IsTurboprop", resourceCulture);
            }
        }
    }
}
